[D Aug-03 20:36:37.183 polycomm_helper:39] Removed Existing BMAP Downloaded version from:-> C:\Spitfire\PeerUnderflowTrackerModule\.bmap_download
[I Aug-03 20:36:37.768 bmap_plugin:78] bmap_version=None, bmap_build=None, bmap_branch=None, bmap_parser_type=BmapFileType.PYTHON
[I Aug-03 20:36:37.820 conftest_plugin:417] Automation stared  : 2023-08-03 20:36:37.820350
[I Aug-03 20:36:37.861 polycomm_helper:130] Sleeping for 3 seconds to load Device Manager...
[D Aug-03 20:36:48.239 dut:100] Initializing Dut None with mac=None
[D Aug-03 20:36:48.472 dut:100] Initializing Dut None with mac=None
[I Aug-03 20:36:48.675 dut_session_fixture_helper:145] Getting default Dut
[I Aug-03 20:36:48.677 dut_session_fixture_helper:148] Current Operating System is:-> windows
[I Aug-03 20:36:48.679 dut_session_fixture_helper:164] [<WearableTestUtils.DutUtils.dut.Dut object at 0x000002438A6FE2E0>, <WearableTestUtils.DutUtils.dut.Dut object at 0x000002438A714400>]
[I Aug-03 20:36:48.759 PbManager:374] Loading proto 'component_state'
[I Aug-03 20:36:48.778 PbManager:374] Loading proto 'core_address'
[I Aug-03 20:36:48.781 PbManager:374] Loading proto 'core_api'
[I Aug-03 20:36:48.783 PbManager:374] Loading proto 'core_handover'
[I Aug-03 20:36:48.786 PbManager:374] Loading proto 'core_msg_header'
[I Aug-03 20:36:48.787 PbManager:374] Loading proto 'cor_reboot_info'
[I Aug-03 20:36:48.790 PbManager:374] Loading proto 'cor_reboot_reason'
[I Aug-03 20:36:48.793 PbManager:374] Loading proto 'cor_shutdown_reason'
[I Aug-03 20:36:48.796 PbManager:374] Loading proto 'media_player_drv_state'
[I Aug-03 20:36:48.798 PbManager:374] Loading proto 'nanopb'
[I Aug-03 20:36:48.801 PbManager:374] Loading proto 'tco_api'
[I Aug-03 20:36:48.803 PbManager:374] Loading proto 'telephony_drv_state'
[W Aug-03 20:36:48.805 PbManager:396] No entry for proto `component_state` found in loaded metadata
[W Aug-03 20:36:48.807 PbManager:396] No entry for proto `cor_reboot_info` found in loaded metadata
[W Aug-03 20:36:48.809 PbManager:396] No entry for proto `cor_reboot_reason` found in loaded metadata
[W Aug-03 20:36:48.811 PbManager:396] No entry for proto `cor_shutdown_reason` found in loaded metadata
[W Aug-03 20:36:48.813 PbManager:396] No entry for proto `nanopb` found in loaded metadata
[W Aug-03 20:36:48.815 PbManager:396] No entry for proto `tco_api` found in loaded metadata
[I Aug-03 20:36:48.817 PbManager:410] Loaded 12 protobufs
[W Aug-03 20:36:48.890 PbManager:396] No entry for proto `component_state` found in loaded metadata
[W Aug-03 20:36:48.892 PbManager:396] No entry for proto `cor_reboot_info` found in loaded metadata
[W Aug-03 20:36:48.894 PbManager:396] No entry for proto `cor_reboot_reason` found in loaded metadata
[W Aug-03 20:36:48.896 PbManager:396] No entry for proto `cor_shutdown_reason` found in loaded metadata
[W Aug-03 20:36:48.898 PbManager:396] No entry for proto `nanopb` found in loaded metadata
[W Aug-03 20:36:48.901 PbManager:396] No entry for proto `tco_api` found in loaded metadata
[I Aug-03 20:36:48.903 PbManager:410] Loaded 12 protobufs
[I Aug-03 20:36:48.906 conftest_plugin:460] Invoking logread fixture
[I Aug-03 20:36:48.911 conftest_plugin:498] -----------------------
[I Aug-03 20:36:48.913 conftest_plugin:499] TEST SETUP PASSED
[I Aug-03 20:36:48.913 conftest_plugin:500] Test: test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:36:48.913 conftest_plugin:501] DateTime: 2023-08-03 20:36:48.913237
[I Aug-03 20:36:48.914 conftest_plugin:502] ------------------------
[I Aug-03 20:36:48.914 test_peerUnderflowTracker:147] Current DUT device is: Scotty [M308000151388105501A0C0]
[D Aug-03 20:36:48.916 SpitfireMessaging:400] Sending request with transaction id 0 (0x0)
[D Aug-03 20:36:48.927 SpitfireMessaging:592] __dispatch_message: success
[D Aug-03 20:36:48.985 dut:180] Received data from [M308000151388105501A0C0] is: [14, 0, 2, 0, 10, 3, 99, 111, 114, 18, 3, 99, 111, 114, 24, 2, 32, 21, 8, 1]
[W Aug-03 20:36:48.987 SpitfireMessaging:709] No meta data for comp_abv 'cor'
[W Aug-03 20:36:48.988 SpitfireMessaging:624] Failed to parse header/payload from incoming mesage
[E Aug-03 20:36:53.937 test_peerUnderflowTracker:89] Error: No response recieved
    assert False
[I Aug-03 20:36:54.418 conftest_plugin:505] -----------------------
[I Aug-03 20:36:54.419 conftest_plugin:506] TEST FAILED
[I Aug-03 20:36:54.419 conftest_plugin:507] Test: test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:36:54.420 conftest_plugin:508] DateTime: 2023-08-03 20:36:54.420405
[E Aug-03 20:36:54.420 conftest_plugin:509] Error: test_peerUnderflowTracker.py:85: in send_request_and_validate
        assert False, f"Error: No response recieved"
    E   AssertionError: Error: No response recieved
    E   assert False
    
    During handling of the above exception, another exception occurred:
    test_peerUnderflowTracker.py:213: in test_track_peer_underflow
        track_peer_underflow(messaging_list, underflowTimeout)
    test_peerUnderflowTracker.py:152: in track_peer_underflow
        dut_payload = send_request_and_validate( msgdev, core_api_pb2.COR_BT_GET_ROLE, payload )
    test_peerUnderflowTracker.py:90: in send_request_and_validate
        assert False
    E   assert False
[I Aug-03 20:36:54.421 conftest_plugin:510] ------------------------
[W Aug-03 20:36:54.428 session_fixture:201] Unable to clear PyDbg Executors for DUT-> Scotty R4C84. Value-> None
[W Aug-03 20:36:54.429 session_fixture:201] Unable to clear PyDbg Executors for DUT-> Scotty L5164. Value-> None
[D Aug-03 20:36:54.430 spitfire_command_helper:233] getting ELF file from directory:-> 'C:\Spitfire'
[D Aug-03 20:37:00.340 spitfire_command_helper:236] Selected ELF file is:-> C:\Spitfire\LoneStarr.elf
[D Aug-03 20:37:00.344 dut:293] Dut Scotty R4C84 connection status changed to -> False
[D Aug-03 20:37:00.357 dut:293] Dut Scotty L5164 connection status changed to -> False
[I Aug-03 20:37:00.473 conftest_plugin:434] Automation completed  : 2023-08-03 20:37:00.473140
[I Aug-03 20:37:00.526 conftest_plugin:520] =================== TEST RESULTS ====================
[I Aug-03 20:37:00.526 conftest_plugin:535]  Passed: 0
[I Aug-03 20:37:00.526 conftest_plugin:538]  Failed: 1
[I Aug-03 20:37:00.526 conftest_plugin:540]    test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:37:00.527 conftest_plugin:549]  Errors: 0
[I Aug-03 20:37:00.527 conftest_plugin:556]  Skipped: 0
[I Aug-03 20:37:00.527 conftest_plugin:559] =========== Passed 0, Failed 1, Error 0, Skipped 0 in 22.7 seconds =============
