[D Aug-03 20:12:00.569 polycomm_helper:39] Removed Existing BMAP Downloaded version from:-> C:\Spitfire\PeerUnderflowTrackerModule\.bmap_download
[I Aug-03 20:12:01.179 bmap_plugin:78] bmap_version=None, bmap_build=None, bmap_branch=None, bmap_parser_type=BmapFileType.PYTHON
[I Aug-03 20:12:01.234 conftest_plugin:417] Automation stared  : 2023-08-03 20:12:01.234434
[I Aug-03 20:12:01.270 polycomm_helper:130] Sleeping for 3 seconds to load Device Manager...
[D Aug-03 20:12:11.538 dut:100] Initializing Dut None with mac=None
[D Aug-03 20:12:11.746 dut:100] Initializing Dut None with mac=None
[I Aug-03 20:12:11.947 dut_session_fixture_helper:145] Getting default Dut
[I Aug-03 20:12:11.949 dut_session_fixture_helper:148] Current Operating System is:-> windows
[I Aug-03 20:12:11.951 dut_session_fixture_helper:164] [<WearableTestUtils.DutUtils.dut.Dut object at 0x0000023C72945BE0>, <WearableTestUtils.DutUtils.dut.Dut object at 0x0000023C7294BD60>]
[I Aug-03 20:12:12.030 PbManager:374] Loading proto 'component_state'
[I Aug-03 20:12:12.050 PbManager:374] Loading proto 'core_address'
[I Aug-03 20:12:12.052 PbManager:374] Loading proto 'core_api'
[I Aug-03 20:12:12.054 PbManager:374] Loading proto 'core_handover'
[I Aug-03 20:12:12.056 PbManager:374] Loading proto 'core_msg_header'
[I Aug-03 20:12:12.058 PbManager:374] Loading proto 'cor_reboot_info'
[I Aug-03 20:12:12.061 PbManager:374] Loading proto 'cor_reboot_reason'
[I Aug-03 20:12:12.065 PbManager:374] Loading proto 'cor_shutdown_reason'
[I Aug-03 20:12:12.068 PbManager:374] Loading proto 'media_player_drv_state'
[I Aug-03 20:12:12.069 PbManager:374] Loading proto 'nanopb'
[I Aug-03 20:12:12.071 PbManager:374] Loading proto 'tco_api'
[I Aug-03 20:12:12.073 PbManager:374] Loading proto 'telephony_drv_state'
[W Aug-03 20:12:12.075 PbManager:396] No entry for proto `component_state` found in loaded metadata
[W Aug-03 20:12:12.077 PbManager:396] No entry for proto `cor_reboot_info` found in loaded metadata
[W Aug-03 20:12:12.079 PbManager:396] No entry for proto `cor_reboot_reason` found in loaded metadata
[W Aug-03 20:12:12.081 PbManager:396] No entry for proto `cor_shutdown_reason` found in loaded metadata
[W Aug-03 20:12:12.083 PbManager:396] No entry for proto `nanopb` found in loaded metadata
[W Aug-03 20:12:12.085 PbManager:396] No entry for proto `tco_api` found in loaded metadata
[I Aug-03 20:12:12.087 PbManager:410] Loaded 12 protobufs
[W Aug-03 20:12:12.153 PbManager:396] No entry for proto `component_state` found in loaded metadata
[W Aug-03 20:12:12.154 PbManager:396] No entry for proto `cor_reboot_info` found in loaded metadata
[W Aug-03 20:12:12.156 PbManager:396] No entry for proto `cor_reboot_reason` found in loaded metadata
[W Aug-03 20:12:12.158 PbManager:396] No entry for proto `cor_shutdown_reason` found in loaded metadata
[W Aug-03 20:12:12.160 PbManager:396] No entry for proto `nanopb` found in loaded metadata
[W Aug-03 20:12:12.162 PbManager:396] No entry for proto `tco_api` found in loaded metadata
[I Aug-03 20:12:12.164 PbManager:410] Loaded 12 protobufs
[I Aug-03 20:12:12.167 conftest_plugin:460] Invoking logread fixture
[I Aug-03 20:12:12.171 conftest_plugin:498] -----------------------
[I Aug-03 20:12:12.173 conftest_plugin:499] TEST SETUP PASSED
[I Aug-03 20:12:12.174 conftest_plugin:500] Test: test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:12:12.174 conftest_plugin:501] DateTime: 2023-08-03 20:12:12.174379
[I Aug-03 20:12:12.174 conftest_plugin:502] ------------------------
[I Aug-03 20:12:12.175 test_peerUnderflowTracker:147] Current DUT device is: Scotty [M308000151388105501A0C0]
[D Aug-03 20:12:12.177 SpitfireMessaging:400] Sending request with transaction id 0 (0x0)
[D Aug-03 20:12:12.188 SpitfireMessaging:592] __dispatch_message: success
[W Aug-03 20:12:12.226 SpitfireMessaging:709] No meta data for comp_abv 'cor'
[W Aug-03 20:12:12.228 SpitfireMessaging:624] Failed to parse header/payload from incoming mesage
[D Aug-03 20:12:12.229 dut:180] Received data from [M308000151388105501A0C0] is: [14, 0, 0, 0, 10, 3, 99, 111, 114, 18, 3, 99, 111, 114, 24, 2, 32, 21]
[E Aug-03 20:12:17.198 test_peerUnderflowTracker:89] Error: No response recieved
    assert False
[I Aug-03 20:12:17.838 conftest_plugin:505] -----------------------
[I Aug-03 20:12:17.839 conftest_plugin:506] TEST FAILED
[I Aug-03 20:12:17.839 conftest_plugin:507] Test: test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:12:17.839 conftest_plugin:508] DateTime: 2023-08-03 20:12:17.839303
[E Aug-03 20:12:17.840 conftest_plugin:509] Error: test_peerUnderflowTracker.py:85: in send_request_and_validate
        assert False, f"Error: No response recieved"
    E   AssertionError: Error: No response recieved
    E   assert False
    
    During handling of the above exception, another exception occurred:
    test_peerUnderflowTracker.py:214: in test_track_peer_underflow
        track_peer_underflow(messaging_list, underflowTimeout)
    test_peerUnderflowTracker.py:153: in track_peer_underflow
        dut_payload = send_request_and_validate( msgdev, core_api_pb2.COR_BT_GET_ROLE, payload )
    test_peerUnderflowTracker.py:90: in send_request_and_validate
        assert False
    E   assert False
[I Aug-03 20:12:17.840 conftest_plugin:510] ------------------------
[W Aug-03 20:12:17.850 session_fixture:201] Unable to clear PyDbg Executors for DUT-> Scotty R4C84. Value-> None
[W Aug-03 20:12:17.852 session_fixture:201] Unable to clear PyDbg Executors for DUT-> Scotty L5164. Value-> None
[D Aug-03 20:12:17.854 spitfire_command_helper:233] getting ELF file from directory:-> 'C:\Spitfire'
[D Aug-03 20:12:22.808 spitfire_command_helper:236] Selected ELF file is:-> C:\Spitfire\LoneStarr.elf
[D Aug-03 20:12:22.811 dut:293] Dut Scotty R4C84 connection status changed to -> False
[D Aug-03 20:12:22.816 dut:293] Dut Scotty L5164 connection status changed to -> False
[I Aug-03 20:12:22.982 conftest_plugin:434] Automation completed  : 2023-08-03 20:12:22.982178
[I Aug-03 20:12:23.031 conftest_plugin:520] =================== TEST RESULTS ====================
[I Aug-03 20:12:23.031 conftest_plugin:535]  Passed: 0
[I Aug-03 20:12:23.032 conftest_plugin:538]  Failed: 1
[I Aug-03 20:12:23.032 conftest_plugin:540]    test_peerUnderflowTracker.py::test_track_peer_underflow
[I Aug-03 20:12:23.032 conftest_plugin:549]  Errors: 0
[I Aug-03 20:12:23.032 conftest_plugin:556]  Skipped: 0
[I Aug-03 20:12:23.032 conftest_plugin:559] =========== Passed 0, Failed 1, Error 0, Skipped 0 in 21.79 seconds =============
